services:
    admin.category:
        class: TestBundle\Admin\CategoryAdmin
        arguments: [~, TestBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Categories }
    admin.product:
        class: TestBundle\Admin\ProductAdmin
        arguments: [~, TestBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Products }            