TestBundle\Entity\Product:
    type: entity
    table: products
    uniqueConstraints:
        UNIQ_B3BA5A5A5E237E06:
            columns:
                - name
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToMany:
        categories:
            targetEntity: Category
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: products
            joinTable:
                name: products_categories_crossref
                joinColumns:
                    -
                        name: product_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: category_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
